language: node_js

node_js:
- '8'
- '9'
- '10'
- '11'

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
- export PATH=$HOME/.yarn/bin:$PATH

before_script:
- yarn
- yarn bootstrap

script:
  - yarn build
  - yarn testAll

after_success:
- test $TRAVIS_NODE_VERSION = 10 && yarn coveralls

cache:
  yarn: true

branches:
  only:
    - master
    - greenkeeper/*
    - /^greenkeeper/.*$/

notifications:
  email: false
